---
- name: ensure target install dir exists
  become: yes
  become_user: root
  file: >-
    path={{binpack_target_dir}}
    state=directory
    mode=0755

- name: install files...
  become: yes
  become_user: root
  with_items: '{{binpack_files|default([])}}'
  copy: >-
    src={{item.f}}
    dest={{binpack_target_dir}}/{{item.f}}
    mode={{item.m|default(0755)}}

- name: templatize...
  become: yes
  become_user: root
  with_items: '{{binpack_templates|default([])}}'
  template: >-
    src={{item.f}}.j2
    dest={{binpack_target_dir}}/{{item.f}}
    mode={{item.m|default(0755)}}

- name: link files...
  become: yes
  become_user: root
  with_items: '{{binpack_templates|default([])}} + {{binpack_files|default([])}}'
  file: >-
    src={{binpack_target_dir}}/{{item.f}}
    dest={{binpack_link_dir}}/{{item.f}}
    state=link

